safe:        true

baseurl:     /localo    

#url: 
source:      ./
destination: ./_site
plugins:     ./_plugins
future:      true
lsi:         false
highlighter:    

markdown:    kramdown
highlighter:    
permalink:   :category/:title/

exclude:
- src
- CNAME
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- VERSION

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: ''
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed